// 12 template link-in-bio. Deskripsi dan halaman dalam mengikuti isi tiap template (1 Okt 2026);
// pratinjau 4:5 ditangkap dari demo live di lebar ponsel.
export const templates = [
  { url: "https://linkinbio-nova.vercel.app", name: "Nova", description: "Aurora gelap untuk creative technologist — studi kasus bernomor dan halaman kolaborasi bertarif.", halaman: ["/karya", "/kolaborasi"], image: "/images/bio/nova.webp", category: "Kreator", tags: ["Dark", "Glass", "Portofolio"] },
  { url: "https://linkinbio-atlas.vercel.app", name: "Atlas", description: "Kartu nama split-screen bergaya Swiss — indeks karya, layanan berharga tetap, dan pemilih slot pertemuan.", halaman: ["/karya", "/layanan"], image: "/images/bio/atlas.webp", category: "Bisnis", tags: ["Swiss", "Studio", "Booking"] },
  { url: "https://linkinbio-mellow.vercel.app", name: "Mellow", description: "Papan stiker pastel untuk ilustrator — toko sticker berkeranjang dan komisi dengan estimasi harga langsung.", halaman: ["/toko", "/komisi"], image: "/images/bio/mellow.webp", category: "Kreator", tags: ["Pastel", "Toko", "Komisi"] },
  { url: "https://linkinbio-pulse.vercel.app", name: "Pulse", description: "Tautan tipografi neon untuk motion designer — lembar cue showreel yang bisa digeser dan rate card.", halaman: ["/showreel", "/hire"], image: "/images/bio/pulse.webp", category: "Kreator", tags: ["Neon", "Motion", "Rate card"] },
  { url: "https://linkinbio-vendra.vercel.app", name: "Vendra", description: "Etalase kedai kopi — status buka menurut jam WIB, menu lengkap, dan pre-order dengan jam ambil.", halaman: ["/menu", "/pesan"], image: "/images/bio/vendra.webp", category: "Bisnis", tags: ["Kafe", "Pre-order", "UMKM"] },
  { url: "https://linkinbio-disko.vercel.app", name: "Disko", description: "Poster Memphis untuk band — tur enam kota dengan pemilih tiket dan merch berstok per ukuran.", halaman: ["/jadwal", "/merch"], image: "/images/bio/disko.webp", category: "Musik", tags: ["Memphis", "Tiket", "Merch"] },
  { url: "https://linkinbio-zen.vercel.app", name: "Zen", description: "Ruang teduh serif untuk coach mindfulness — kelas, retret, dan pemandu napas interaktif.", halaman: ["/kelas", "/napas"], image: "/images/bio/zen.webp", category: "Lifestyle", tags: ["Minimal", "Serif", "Interaktif"] },
  { url: "https://linkinbio-cipher.vercel.app", name: "Cipher", description: "Terminal CRT untuk peneliti keamanan — writeup CTF, kebijakan pengungkapan, dan talks.", halaman: ["/writeups", "/talks"], image: "/images/bio/cipher.webp", category: "Teknologi", tags: ["Terminal", "CRT", "Developer"] },
  { url: "https://linkinbio-vinyl.vercel.app", name: "Vinyl", description: "Piringan berputar untuk musisi — album dengan penggalan lirik, tur akustik, dan pengingat tiket.", halaman: ["/album", "/tur"], image: "/images/bio/vinyl.webp", category: "Musik", tags: ["Musisi", "Album", "Tur"] },
  { url: "https://linkinbio-arsip.vercel.app", name: "Arsip", description: "Surat bergaris untuk penulis — buku dengan satu puisi utuh, surat Jumat, dan kelas menulis.", halaman: ["/buku", "/surat"], image: "/images/bio/arsip.webp", category: "Kreator", tags: ["Vintage", "Mesin ketik", "Penulis"] },
  { url: "https://linkinbio-jajan.vercel.app", name: "Jajan", description: "Papan menu warung — buka/tutup menurut jam WIB, menu lengkap, dan PO acara dengan minimal H-2.", halaman: ["/menu", "/pesan"], image: "/images/bio/jajan.webp", category: "Bisnis", tags: ["Kuliner", "UMKM", "PO"] },
  { url: "https://linkinbio-kaset.vercel.app", name: "Kaset", description: "Mixtape analog untuk radio komunitas — siaran berikutnya dihitung otomatis dan arsip bertracklist.", halaman: ["/siaran", "/mixtape"], image: "/images/bio/kaset.webp", category: "Musik", tags: ["Analog", "Radio", "Jadwal"] },
];
